dedi_sylius_seo_plugin_seo_admin:
  resource: |
    alias: dedi_sylius_seo_plugin.seo_content
    section: admin
    templates: "@SyliusAdmin\\Crud"
    grid: dedi_sylius_seo_plugin.seo_content
    except: ['show']
    permission: true
    vars:
        all:
            subheader: dedi_sylius_seo_plugin.ui.seo_content_subtitle
            templates:
                form: "@DediSyliusSEOPlugin/Admin/SEO/Form/_form.html.twig"
        index:
            icon: 'search'
  type: sylius.resource

dedi_sylius_seo_plugin_admin_seo_content_create:
  path: /seo-contents/{type}/new
  methods: [GET, POST]
  defaults:
    _controller: dedi_sylius_seo_plugin.controller.seo_content::createAction
    _sylius:
      section: admin
      factory:
        method: createTyped
        arguments:
          type: $type
      template: "@SyliusAdmin/Crud/create.html.twig"
      redirect: dedi_sylius_seo_plugin_admin_seo_content_update
      permission: true
      vars:
        subheader: dedi_sylius_seo_plugin.ui.seo_content_subtitle
        templates:
          form: "@DediSyliusSEOPlugin/Admin/SEO/Form/_form.html.twig"
        route:
          parameters:
            type: $type