sylius_grid:
    grids:
        dedi_sylius_seo_plugin.seo_content:
            driver:
                name: doctrine/orm
                options:
                    class: "%dedi_sylius_seo_plugin.model.seo_content.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: [ "expr:service('sylius.context.locale').getLocaleCode()" ]
            sorting:
                metadataTitle: asc
            fields:
                type:
                    type: twig
                    label: sylius.ui.type
                    options:
                        template: "@DediSyliusSEOPlugin/admin/seo_content/grid/field/type.html.twig"
                resource:
                    type: twig
                    label: dedi_sylius_seo_plugin.ui.resource
                    path: .
                    sortable: false
                    options:
                        template: "@DediSyliusSEOPlugin/admin/seo_content/grid/field/resource.html.twig"
                metadataTitle:
                    type: string
                    label: dedi_sylius_seo_plugin.form.metadata_title
                    sortable: translation.metadataTitle
                metadataDescription:
                    type: string
                    label: dedi_sylius_seo_plugin.form.metadata_description
                    sortable: translation.metadataDescription
                notIndexable:
                    type: twig
                    label: dedi_sylius_seo_plugin.ui.indexable
                    path: robot.isNotIndexable
                    options:
                        template: "@DediSyliusSEOPlugin/admin/seo_content/grid/field/indexable.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [ translation.metadataTitle, translation.metadataDescription ]
                product:
                    type: ux_translatable_autocomplete
                    label: sylius.ui.product
                    form_options:
                        multiple: false
                        extra_options:
                            class: '%sylius.model.product.class%'
                            translation_fields: [name]
                            choice_label: name
                taxon:
                    type: ux_translatable_autocomplete
                    label: sylius.ui.taxon
                    form_options:
                        multiple: false
                        extra_options:
                            class: '%sylius.model.taxon.class%'
                            translation_fields: [name]
                            choice_label: fullname
                uri:
                    type: string
                    label: URI
                    form_options:
                        type: contains
                    options:
                        fields: [ translation.uri ]
                channel:
                    type: entity
                    label: sylius.ui.channel
                    form_options:
                        class: "%sylius.model.channel.class%"
                    options:
                        field: channel.id
                indexable:
                    type: boolean

            actions:
                main:
                    create:
                        type: links
                        label: sylius.ui.create
                        options:
                            class: primary
                            icon: "tabler:plus"
                            header:
                                icon: "tabler:search"
                                label: sylius.ui.type
                            links:
                                product:
                                    label: dedi_sylius_seo_plugin.ui.seo_for_product
                                    route: dedi_sylius_seo_plugin_admin_seo_content_create
                                    parameters:
                                        type: product
                                taxon:
                                    label: dedi_sylius_seo_plugin.ui.seo_for_taxon
                                    route: dedi_sylius_seo_plugin_admin_seo_content_create
                                    parameters:
                                        type: taxon
                                url:
                                    label: dedi_sylius_seo_plugin.ui.seo_for_url
                                    route: dedi_sylius_seo_plugin_admin_seo_content_create
                                    parameters:
                                        type: uri
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
