sylius_resource:
    resources:
        dedi_sylius_seo_plugin.seo_content:
            driver: doctrine/orm
            classes:
                model: Dedi\SyliusSEOPlugin\Entity\SEOContent
                form: Dedi\SyliusSEOPlugin\Form\Type\SEOContentType
            translation:
                classes:
                    model: Dedi\SyliusSEOPlugin\Entity\SEOContentTranslation
                    factory: Sylius\Component\Resource\Factory\TranslatableFactory
                    form: Dedi\SyliusSEOPlugin\Form\Type\SEOContentTranslationType
