name: Rebase

on:
    workflow_run:
        branches:
            - master
        workflows:
            - CI
        types:
            - completed

jobs:
    rebase:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: dediagency/sylius-workflows/.github/workflows/rebase.yml@v1
        secrets: inherit
        with:
            base: master
