name: Release

on:
    workflow_run:
        branches:
            - master
        workflows:
            - CI
        types:
            - completed

jobs:
    release:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: dediagency/sylius-workflows/.github/workflows/release.yml@v1
        secrets: inherit
